# Plugin Kubernetes
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      exposeDashboard: true
      clusters:
        - url: https://kubernetes.default.svc
          name: k3d-mycluster
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          dashboardApp: 'headlamp'
          dashboardParameters:
            internal: true
            headlampRoute: '/headlamp' # Optional, defaults to '/headlamp'
            clusterName: 'my-cluster' # Optional, defaults to 'default'

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: false
