name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_TAG: ${{ github.ref_name }}
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  FRONTEND_IMAGE_NAME: backstage-frontend
  BACKEND_IMAGE_NAME: backstage-backend
  CONTEXT_DIR: vanilla

jobs:
  build-push-frontend:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      id-token: write
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      runner: amd64
      setup-qemu: true
      file: Containerfile.frontend
      sbom: true
      context: vanilla
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/backstage-frontend
      meta-tags: |
        type=ref,event=tag
        latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-push-backend:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login \
            ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      # Needed for Makefile
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Remove frontend from backend
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-frontend-from-backend

      - name: Remove better-sqlite3
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-better-sqlite3

      - name: Build and push backend container image
        uses: docker/build-push-action@v6
        with:
          context: vanilla
          platforms: linux/amd64,linux/arm64
          file: Containerfile.backend
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

  scan:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    needs:
      - build-push-frontend
      - build-push-backend
    steps:
      - name: Docker Scout - backend
        uses: docker/scout-action@v1
        with:
          command: cves
          sarif-file: sarif-backend.output.json
          summary: true
          image: registry://${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Upload backend SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sarif-backend.output.json

      - name: Docker Scout - frontend
        uses: docker/scout-action@v1
        with:
          command: cves
          sarif-file: sarif-frontend.output.json
          summary: true
          image: registry://${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Upload frontend SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sarif-frontend.output.json
